# Generated by Django 5.2.4 on 2025-07-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_todo_completion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_completion',
            new_name='todo_status',
        ),
    ]
