# Generated by Django 5.2.4 on 2025-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_todo_completion_todo_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
