# Generated by Django 5.2.4 on 2025-07-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_todo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskid', to='todoapp.taskid'),
        ),
    ]
