# Generated by Django 5.2.4 on 2025-07-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_taskid_alter_todo_todo_status_todo_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
