# Generated by Django 5.2.5 on 2025-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskid',
            name='task_id',
            field=models.CharField(max_length=20),
        ),
    ]
